"""Export web/assets/orientation-experiment-data.js for the Orientation Lab page.

Distances/verdict come verbatim from results/results-orientation.json (the canonical
experiment output). Display curves (two-sided MI, internal quench S_A) are regenerated
here for EVERY sweep g at (N=256, beta=1) through the exact same modules the experiment
used — the driver only stores curves at g in {0, 0.1}.

Run:  .venv/bin/python3 src/export-web-orientation-data.py
"""
import importlib.util, json, pathlib, sys
import numpy as np

SRC = pathlib.Path(__file__).parent
ROOT = SRC.parent


def _load(fname, modname):
    if modname in sys.modules:
        return sys.modules[modname]
    spec = importlib.util.spec_from_file_location(modname, SRC / fname)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[modname] = mod
    spec.loader.exec_module(mod)
    return mod


ts = _load("tfd-gaussian-state-construction.py", "tfd_state")
oe = _load("orientation-flip-evolution.py", "orientation_evolution")
bt = _load("internal-battery-side-r.py", "internal_battery")
ge = _load("gods-eye-discriminators.py", "gods_eye")

N, BETA, V_QUENCH = 256, 1.0, 3.0


def curves_for_g(st, scr, g):
    """MI(t) for mirror O+/O- and quench S_A(t/tick) for all four variants."""
    out = {"mi_t": ge.GE_TIMES.tolist()}
    for s, comp, state in ((+1, "mirror", st), (-1, "mirror", st),
                           (+1, "scrambled", scr), (-1, "scrambled", scr)):
        key = f"O{'+' if s > 0 else '-'}{comp}"
        if comp == "mirror":
            evo_main = oe.VariantEvolution(oe.build_variant_h1(N, s, g),
                                           state["G"], state["F"])
            out[f"mi_{'plus' if s > 0 else 'minus'}"] = \
                ge.mutual_information_curve(evo_main, N).tolist()
        Gk, Fk = bt.apply_clock_kick(state["G"], state["F"], N)
        clk = oe.VariantEvolution(oe.build_variant_h1(N, s, g, carve=True), Gk, Fk)
        m = bt.clock_measurement(clk, N, oe.cavity_specs(N)[0])
        tick = 2.0 * np.pi / m["omega"]
        evq = oe.VariantEvolution(
            oe.build_variant_h1(N, s, g, quench=(N // 2, V_QUENCH)),
            state["G"], state["F"])
        out.setdefault("sa", {})[key] = bt.quench_arrow_item(evq, N, tick).tolist()
        out.setdefault("ticks", {})[key] = tick
    out["sa_t_ticks"] = (np.arange(25) / 8.0).tolist()
    return out


def main():
    res = json.load(open(ROOT / "results" / "results-orientation.json"))
    sweep = sorted([r for r in res["records"]
                    if r["N"] == N and r["beta"] == BETA], key=lambda r: r["g"])
    gs = [r["g"] for r in sweep]

    st = ts.build_tfd(N, BETA)
    scr = ts.scramble_l_sector(st)
    curves = {}
    for g in gs:
        print(f"  regenerating curves at g={g:g}", flush=True)
        curves[f"{g:g}"] = curves_for_g(st, scr, g)

    payload = {
        "N": N, "beta": BETA, "gs": gs,
        "verdict": res["verdict"],
        "rod": sweep[0]["rod"],
        "records": [{"g": r["g"],
                     "D_orientation": r["internal"]["orientation-mirror"]["D"],
                     "D_purification": r["internal"]["purification"]["D"],
                     "items_orientation": r["internal"]["orientation-mirror"]["items"],
                     "items_purification": r["internal"]["purification"]["items"],
                     "gods_eye": r["gods_eye"]} for r in sweep],
        "curves": curves,
    }
    out = ROOT / "web" / "assets" / "orientation-experiment-data.js"
    out.write_text("// Generated by src/export-web-orientation-data.py from\n"
                   "// results/results-orientation.json + exact curve regeneration.\n"
                   "const ORIENTATION_DATA = " + json.dumps(payload) + ";\n")
    print(f"wrote {out}", flush=True)


if __name__ == "__main__":
    main()
